import type { User, Course, Module, Lecture, Assignment, Grade, CalendarEvent, Todo, Notification, Analytics, StudyPlan } from "@/types";

export const mockUser: User = {
  id: "u001",
  name: "Alex Johnson",
  email: "alex.johnson@dezigncamp.edu",
  role: "student",
  studentId: "DC-2024-0042",
  department: "Computer Science",
  semester: 4,
  joinedAt: "2024-01-15",
};

export const mockCourses: Course[] = [
  {
    id: "c001",
    title: "Advanced UI/UX Design Fundamentals",
    description: "Master the principles of modern UI/UX design with real-world projects",
    instructorId: "i001",
    instructorName: "Dr. Sarah Chen",
    category: "Design",
    totalLectures: 24,
    completedLectures: 18,
    progress: 75,
    duration: "12h 30m",
    enrolledAt: "2024-01-20",
    lastAccessedAt: "2024-06-28",
    status: "active",
    tags: ["UI", "UX", "Figma", "Design Systems"],
  },
  {
    id: "c002",
    title: "React & Next.js Development",
    description: "Build production-grade web applications with React and Next.js",
    instructorId: "i002",
    instructorName: "Prof. Marcus Wei",
    category: "Development",
    totalLectures: 36,
    completedLectures: 22,
    progress: 61,
    duration: "18h 45m",
    enrolledAt: "2024-01-20",
    lastAccessedAt: "2024-06-30",
    status: "active",
    tags: ["React", "Next.js", "TypeScript", "Frontend"],
  },
  {
    id: "c003",
    title: "Data Structures & Algorithms",
    description: "Comprehensive coverage of DSA for technical interviews and competitive programming",
    instructorId: "i003",
    instructorName: "Dr. Priya Patel",
    category: "Computer Science",
    totalLectures: 48,
    completedLectures: 48,
    progress: 100,
    duration: "24h 00m",
    enrolledAt: "2024-01-20",
    lastAccessedAt: "2024-05-15",
    status: "completed",
    tags: ["DSA", "Algorithms", "Python", "C++"],
  },
  {
    id: "c004",
    title: "Machine Learning with Python",
    description: "From linear regression to deep neural networks — hands-on ML engineering",
    instructorId: "i004",
    instructorName: "Prof. Ahmed Hassan",
    category: "AI/ML",
    totalLectures: 42,
    completedLectures: 8,
    progress: 19,
    duration: "21h 15m",
    enrolledAt: "2024-02-10",
    lastAccessedAt: "2024-06-25",
    status: "active",
    tags: ["ML", "Python", "TensorFlow", "Data Science"],
  },
];

export const mockAssignments: Assignment[] = [
  {
    id: "a001",
    courseId: "c001",
    title: "Design System Component Library",
    description: "Create a comprehensive design system with at least 20 components in Figma",
    type: "assignment",
    dueDate: "2024-07-10",
    totalMarks: 100,
    status: "pending",
  },
  {
    id: "a002",
    courseId: "c002",
    title: "Full-Stack Todo Application",
    description: "Build a full-stack todo app with Next.js, Prisma, and PostgreSQL",
    type: "assignment",
    dueDate: "2024-07-05",
    totalMarks: 100,
    submittedAt: "2024-07-03",
    score: 87,
    status: "graded",
  },
  {
    id: "a003",
    courseId: "c002",
    title: "Mid-Term Quiz",
    description: "React hooks, state management, and performance optimization",
    type: "quiz",
    dueDate: "2024-07-15",
    totalMarks: 50,
    status: "pending",
  },
  {
    id: "a004",
    courseId: "c004",
    title: "Linear Regression Project",
    description: "Implement linear regression from scratch and on a real dataset",
    type: "assignment",
    dueDate: "2024-06-28",
    totalMarks: 100,
    status: "overdue",
  },
  {
    id: "a005",
    courseId: "c001",
    title: "UX Case Study Discussion",
    description: "Analyze and discuss a real-world UX failure case study",
    type: "gdb",
    dueDate: "2024-07-08",
    totalMarks: 20,
    status: "pending",
  },
];

export const mockGrades: Grade[] = [
  {
    id: "g001",
    courseId: "c001",
    courseName: "Advanced UI/UX Design Fundamentals",
    assignments: 88,
    quizzes: 92,
    exams: 85,
    gdb: 95,
    total: 89,
    grade: "A",
    semester: "Spring 2024",
  },
  {
    id: "g002",
    courseId: "c002",
    courseName: "React & Next.js Development",
    assignments: 87,
    quizzes: 78,
    exams: 0,
    gdb: 82,
    total: 75,
    grade: "B+",
    semester: "Spring 2024",
  },
  {
    id: "g003",
    courseId: "c003",
    courseName: "Data Structures & Algorithms",
    assignments: 95,
    quizzes: 90,
    exams: 88,
    gdb: 92,
    total: 91,
    grade: "A+",
    semester: "Fall 2023",
  },
];

export const mockCalendarEvents: CalendarEvent[] = [
  {
    id: "e001",
    title: "UI/UX Assignment Deadline",
    description: "Design System Component Library submission",
    startDate: "2024-07-10T23:59:00",
    endDate: "2024-07-10T23:59:00",
    type: "assignment",
    courseId: "c001",
  },
  {
    id: "e002",
    title: "React Mid-Term Quiz",
    startDate: "2024-07-15T10:00:00",
    endDate: "2024-07-15T11:30:00",
    type: "exam",
    courseId: "c002",
  },
  {
    id: "e003",
    title: "Lecture: Neural Networks",
    startDate: "2024-07-05T14:00:00",
    endDate: "2024-07-05T16:00:00",
    type: "lecture",
    courseId: "c004",
  },
  {
    id: "e004",
    title: "Study Session: DSA Review",
    startDate: "2024-07-06T09:00:00",
    endDate: "2024-07-06T11:00:00",
    type: "reminder",
  },
];

export const mockTodos: Todo[] = [
  {
    id: "t001",
    title: "Complete Figma component library",
    description: "At least 20 components with variants",
    dueDate: "2024-07-10",
    priority: "high",
    completed: false,
    courseId: "c001",
    createdAt: "2024-07-01",
  },
  {
    id: "t002",
    title: "Watch React hooks lectures (3–5)",
    priority: "high",
    completed: false,
    courseId: "c002",
    createdAt: "2024-07-01",
  },
  {
    id: "t003",
    title: "Review ML linear regression notes",
    priority: "medium",
    completed: true,
    courseId: "c004",
    createdAt: "2024-06-30",
  },
  {
    id: "t004",
    title: "Post GDB response for UX case study",
    dueDate: "2024-07-08",
    priority: "medium",
    completed: false,
    courseId: "c001",
    createdAt: "2024-07-02",
  },
];

export const mockNotifications: Notification[] = [
  {
    id: "n001",
    title: "Assignment Graded",
    message: "Your Full-Stack Todo Application has been graded: 87/100",
    type: "success",
    isRead: false,
    createdAt: "2024-07-03T14:30:00",
  },
  {
    id: "n002",
    title: "New Lecture Available",
    message: "Prof. Marcus Wei added 'Advanced State Management' to React & Next.js course",
    type: "info",
    isRead: false,
    createdAt: "2024-07-02T09:00:00",
  },
  {
    id: "n003",
    title: "Deadline Reminder",
    message: "UI/UX Design System assignment is due in 7 days",
    type: "warning",
    isRead: true,
    createdAt: "2024-07-01T08:00:00",
  },
  {
    id: "n004",
    title: "Inactivity Alert",
    message: "You haven't accessed the ML course in 5 days. Keep up your study streak!",
    type: "warning",
    isRead: true,
    createdAt: "2024-06-30T10:00:00",
  },
];

export const mockAnalytics: Analytics = {
  totalCourses: 4,
  completedCourses: 1,
  totalWatchTime: 1840,
  averageProgress: 64,
  currentStreak: 7,
  totalNotes: 42,
  submittedAssignments: 8,
  averageGrade: 85,
};

export const mockStudyPlan: StudyPlan = {
  id: "sp001",
  userId: "u001",
  weeklyGoalHours: 20,
  generatedAt: "2024-07-01",
  recommendations: [
    "Focus on ML course — you're significantly behind schedule",
    "Review React hooks before the mid-term quiz on July 15",
    "Your UI/UX progress is strong — maintain 2 sessions/week",
    "Consider early morning sessions for complex DSA reviews",
  ],
  dailySchedule: [
    {
      day: "Monday",
      sessions: [
        { courseId: "c002", courseName: "React & Next.js", duration: 90, startTime: "09:00", topic: "State Management" },
        { courseId: "c004", courseName: "Machine Learning", duration: 60, startTime: "14:00", topic: "Linear Regression" },
      ],
    },
    {
      day: "Tuesday",
      sessions: [
        { courseId: "c001", courseName: "UI/UX Design", duration: 120, startTime: "10:00", topic: "Component Design" },
        { courseId: "c004", courseName: "Machine Learning", duration: 60, startTime: "15:00", topic: "Gradient Descent" },
      ],
    },
    {
      day: "Wednesday",
      sessions: [
        { courseId: "c002", courseName: "React & Next.js", duration: 90, startTime: "09:00", topic: "Next.js App Router" },
        { courseId: "c001", courseName: "UI/UX Design", duration: 60, startTime: "14:00", topic: "Usability Testing" },
      ],
    },
    {
      day: "Thursday",
      sessions: [
        { courseId: "c004", courseName: "Machine Learning", duration: 120, startTime: "09:00", topic: "Neural Networks" },
        { courseId: "c002", courseName: "React & Next.js", duration: 60, startTime: "15:00", topic: "Performance" },
      ],
    },
    {
      day: "Friday",
      sessions: [
        { courseId: "c001", courseName: "UI/UX Design", duration: 90, startTime: "10:00", topic: "Design System" },
        { courseId: "c004", courseName: "Machine Learning", duration: 60, startTime: "14:00", topic: "Evaluation Metrics" },
      ],
    },
    {
      day: "Saturday",
      sessions: [
        { courseId: "c002", courseName: "React & Next.js", duration: 120, startTime: "10:00", topic: "Project Work" },
        { courseId: "c001", courseName: "UI/UX Design", duration: 60, startTime: "14:00", topic: "Portfolio Review" },
      ],
    },
  ],
};
